In [106]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets

In [65]:
diabetes_X,diabetes_y = datasets.load_diabetes(return_X_y=True)

In [69]:
diabetes_X_train = diabetes_X[:-20]
diabetes_X_test = diabetes_X[-20:]
diabetes_y_train = diabetes_y[:-20]
diabetes_y_test = diabetes_y[-20:]
diabetes_X_train

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [-0.02004471, -0.04464164, -0.0547075 , ..., -0.03949338,
        -0.07409261, -0.0052198 ],
       [ 0.02354575, -0.04464164, -0.03638469, ...,  0.03430886,
        -0.03324559,  0.06105391],
       [ 0.03807591,  0.05068012,  0.0164281 , ...,  0.07120998,
         0.0497702 ,  0.01549073]])

In [81]:
bias=np.ones((len(diabetes_X_train),1))
bias

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],

In [83]:
x_new = bias
for coldata in zip(*diabetes_X_train):
  tempArr = np.array(coldata)
  tempNew = tempArr.reshape([-1,1])
  x_new = np.append(x_new,tempNew,axis=1)
x_new

array([[ 1.        ,  0.03807591,  0.05068012, ..., -0.00259226,
         0.01990749, -0.01764613],
       [ 1.        , -0.00188202, -0.04464164, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 1.        ,  0.08529891,  0.05068012, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 1.        , -0.02004471, -0.04464164, ..., -0.03949338,
        -0.07409261, -0.0052198 ],
       [ 1.        ,  0.02354575, -0.04464164, ...,  0.03430886,
        -0.03324559,  0.06105391],
       [ 1.        ,  0.03807591,  0.05068012, ...,  0.07120998,
         0.0497702 ,  0.01549073]])

In [84]:
x_new_transpose = x_new.transpose()
x_new_transpose

array([[ 1.        ,  1.        ,  1.        , ...,  1.        ,
         1.        ,  1.        ],
       [ 0.03807591, -0.00188202,  0.08529891, ..., -0.02004471,
         0.02354575,  0.03807591],
       [ 0.05068012, -0.04464164,  0.05068012, ..., -0.04464164,
        -0.04464164,  0.05068012],
       ...,
       [-0.00259226, -0.03949338, -0.00259226, ..., -0.03949338,
         0.03430886,  0.07120998],
       [ 0.01990749, -0.06833155,  0.00286131, ..., -0.07409261,
        -0.03324559,  0.0497702 ],
       [-0.01764613, -0.09220405, -0.02593034, ..., -0.0052198 ,
         0.06105391,  0.01549073]])

In [85]:
x_new_transpose_dot_x_new = x_new_transpose.dot(x_new)
x_new_transpose_dot_x_new

array([[ 4.22000000e+02,  1.64779176e-01, -6.03848223e-02,
         1.99565928e-01,  1.34065552e-01, -2.24548035e-01,
        -2.27999002e-01, -2.14384601e-01,  4.11439149e-02,
         6.90157947e-02, -1.97977716e-01],
       [ 1.64779176e-01,  9.64232255e-01,  1.54324662e-01,
         1.77095879e-01,  3.12705782e-01,  2.62403185e-01,
         2.15401007e-01, -5.23444190e-02,  1.89073676e-01,
         2.63450178e-01,  2.81142422e-01],
       [-6.03848223e-02,  1.54324662e-01,  9.54386499e-01,
         7.29421401e-02,  2.14176439e-01,  3.68285446e-02,
         1.35889351e-01, -3.49906993e-01,  3.13754961e-01,
         1.38483220e-01,  1.89965410e-01],
       [ 1.99565928e-01,  1.77095879e-01,  7.29421401e-02,
         9.55778160e-01,  3.66044439e-01,  2.45302920e-01,
         2.55679403e-01, -3.40434547e-01,  4.01035367e-01,
         4.21008238e-01,  3.65228411e-01],
       [ 1.34065552e-01,  3.12705782e-01,  2.14176439e-01,
         3.66044439e-01,  9.56061821e-01,  2.36519651e-01,
  

In [86]:
x_new_transpose_dot_x_new_inverse = np.linalg.inv(x_new_transpose_dot_x_new)
x_new_transpose_dot_x_new_inverse

array([[ 2.37181823e-03, -6.61641990e-04,  3.77605771e-04,
        -5.74560512e-04, -3.83979064e-04, -2.79561360e-03,
         3.22439412e-03,  1.74257225e-03, -2.00214895e-04,
         1.12949607e-03,  1.00036384e-03],
       [-6.61641990e-04,  1.26071588e+00, -1.30792797e-01,
        -7.38582630e-03, -2.45464158e-01,  1.72624141e-01,
        -3.20091813e-01, -2.04493380e-01,  5.20631375e-02,
        -2.46070201e-01, -1.75473068e-01],
       [ 3.77605771e-04, -1.30792797e-01,  1.32535025e+00,
         2.11822665e-01, -2.54400422e-01,  4.06211784e-01,
        -2.85061139e-01,  2.28725914e-01, -2.86043872e-01,
         3.97740413e-02, -9.26706489e-02],
       [-5.74560512e-04, -7.38582630e-03,  2.11822665e-01,
         1.55919259e+00, -3.58799820e-01,  7.58338071e-01,
        -7.98781321e-01,  1.10561312e-01,  6.67671032e-03,
        -5.66326568e-01, -2.22695845e-01],
       [-3.83979064e-04, -2.45464158e-01, -2.54400422e-01,
        -3.58799820e-01,  1.50121367e+00, -3.14179751e-01,
  

In [87]:
temp1 = x_new_transpose.dot(diabetes_y_train)
temp1

array([ 6.47190000e+04,  3.21007842e+02,  4.77965278e+01,  9.27264651e+02,
        6.98560379e+02,  3.00873790e+02,  2.39159122e+02, -6.32459142e+02,
        6.78564138e+02,  8.83868261e+02,  5.67349960e+02])

In [88]:
theta = x_new_transpose_dot_x_new_inverse.dot(temp1)
theta

array([ 1.52764292e+02,  3.06094248e-01, -2.37635570e+02,  5.10538048e+02,
        3.27729878e+02, -8.14111926e+02,  4.92799595e+02,  1.02841240e+02,
        1.84603496e+02,  7.43509388e+02,  7.60966464e+01])

In [107]:
diabetes_X_test_data_frame = pd.DataFrame(diabetes_X_test)
diabetes_X_test_data_frame

0         1         2         3         4         5         6  \
0  -0.078165  0.050680  0.077863  0.052858  0.078236  0.064447  0.026550   
1   0.009016  0.050680 -0.039618  0.028758  0.038334  0.073529 -0.072854   
2   0.001751  0.050680  0.011039 -0.019442 -0.016704 -0.003819 -0.047082   
3  -0.078165 -0.044642 -0.040696 -0.081413 -0.100638 -0.112795  0.022869   
4   0.030811  0.050680 -0.034229  0.043666  0.057597  0.068831 -0.032356   
5  -0.034575  0.050680  0.005650 -0.005670 -0.073119 -0.062691 -0.006584   
6   0.048974  0.050680  0.088642  0.087287  0.035582  0.021546 -0.024993   
7  -0.041840 -0.044642 -0.033151 -0.022885  0.046589  0.041587  0.056003   
8  -0.009147 -0.044642 -0.056863 -0.050427  0.021822  0.045345 -0.028674   
9   0.070769  0.050680 -0.030996  0.021872 -0.037344 -0.047034  0.033914   
10  0.009016 -0.044642  0.055229 -0.005670  0.057597  0.044719 -0.002903   
11 -0.027310 -0.044642 -0.060097 -0.029770  0.046589  0.019980  0.122273   
12  0.016281 -0.044642  0.001339  0.008101  0.005311  0.010899  0.030232   
13 -0.012780 -0.044642 -0.023451 -0.040099 -0.016704  0.004636 -0.017629   
14 -0.056370 -0.044642 -0.074108 -0.050427 -0.024960 -0.047034  0.092820   
15  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
16 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
17  0.041708  0.050680 -0.015906  0.017293 -0.037344 -0.013840 -0.024993   
18 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
19 -0.045472 -0.044642 -0.073030 -0.081413  0.083740  0.027809  0.173816   

           7         8         9  
0  -0.002592  0.040673 -0.009362  
1   0.108111  0.015568 -0.046641  
2   0.034309  0.024055  0.023775  
3  -0.076395 -0.020292 -0.050783  
4   0.057557  0.035459  0.085907  
5  -0.039493 -0.045424  0.032059  
6   0.034309  0.066051  0.131470  
7  -0.024733 -0.025953 -0.038357  
8   0.034309 -0.009919 -0.017646  
9  -0.039493 -0.014960 -0.001078  
10  0.023239  0.055686  0.106617  
11 -0.039493 -0.051404 -0.009362  
12 -0.039493 -0.045424  0.032059  
13 -0.002592 -0.038460 -0.038357  
14 -0.076395 -0.061176 -0.046641  
15 -0.002592  0.031193  0.007207  
16  0.034309 -0.018114  0.044485  
17 -0.011080 -0.046883  0.015491  
18  0.026560  0.044529 -0.025930  
19 -0.039493 -0.004222  0.003064

In [112]:
def predict_values(theta, test_data):
    y = []
    for ind in test_data.index:
        y.append(theta[0]) 
        for idx, column in enumerate(test_data.columns):
            y[ind] = y[ind]+theta[idx+1]*test_data[column][ind]
    return y

In [114]:
xyz = diabetes_X_test_data_frame[[0,1,2,3,4,5,6,7,8,9]]
predicted_y = predict_values(theta, xyz)
predicted_y

[197.61898486167436,
 155.44031961942918,
 172.88875143544317,
 111.53270644638708,
 164.79397301122427,
 131.0676586856375,
 259.1244121930071,
 100.47873745848835,
 117.06005372050265,
 124.30261597304953,
 218.36868145767417,
 61.195819441759724,
 132.24837932841822,
 120.33293545686963,
 52.545130087542425,
 194.03746763935771,
 102.57564309947382,
 123.5677870924887,
 211.03465322946954,
 52.602216959195644]

In [118]:
error = diabetes_y_test - predicted_y
absolute_error = np.sum(error)
mean_absolute_error = absolute_error/len(diabetes_X_train)
se = np.sum(error**2)
mse = se/len(diabetes_X_train)
print("Mean absolute error: ",mean_absolute_error)
print("Mean Squared error: ",mse)
print("Root mean Squared error: ",np.sqrt(mse))

Mean absolute error:  -0.6607036189504569
Mean Squared error:  95.00088560825644
Root mean Squared error:  9.746839775448063
